sudo: false
language: scala
scala:
- 2.12.6
- 2.11.12

jobs:
  include:
    - stage: test
      script: sbt test

    - stage: microsite
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.3.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt makeMicrosite

stages:
  - test
  - microsite

jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
